# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20161018_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashoutflow',
            name='account_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cashoutflow',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cashoutflow',
            name='document',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='cashoutflow',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cashoutflow',
            name='purpose',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cashoutflow',
            name='ref_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cashoutflow',
            name='remarks',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
