# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 15:00
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20161018_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_num', models.IntegerField(verbose_name='Reference Number')),
                ('account_title', models.CharField(max_length=100, verbose_name='Account Title')),
                ('account_type', models.CharField(max_length=100, verbose_name='Account Type')),
            ],
            options={
                'verbose_name': 'Chart of Accounts',
            },
        ),
        migrations.RemoveField(
            model_name='cashinflow',
            name='ref_num',
        ),
        migrations.RemoveField(
            model_name='cashoutflow',
            name='ref_num',
        ),
        migrations.AlterField(
            model_name='cashinflow',
            name='account_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.ChartOfAccounts', verbose_name='Account Title'),
        ),
        migrations.AlterField(
            model_name='cashinflow',
            name='document',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='cashoutflow',
            name='account_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.ChartOfAccounts', verbose_name='Account Title'),
        ),
    ]
