# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 15:14
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20161019_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashinflow',
            name='chart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finance.ChartOfAccounts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashinflow',
            name='ref_num',
            field=models.IntegerField(default=1, verbose_name='Reference Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashoutflow',
            name='chart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finance.ChartOfAccounts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashoutflow',
            name='ref_num',
            field=models.IntegerField(default=1, verbose_name='Reference Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashinflow',
            name='account_title',
            field=models.CharField(max_length=100, verbose_name='Account Title'),
        ),
        migrations.AlterField(
            model_name='cashoutflow',
            name='account_title',
            field=models.CharField(max_length=100, verbose_name='Account Title'),
        ),
    ]
