# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20161019_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashinflow',
            name='ref_num',
            field=models.IntegerField(blank=True, verbose_name='Reference Number'),
        ),
    ]
