# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20161019_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashoutflow',
            name='account_title',
            field=models.CharField(max_length=100, verbose_name='Account Title'),
        ),
    ]
