# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 15:52
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20161019_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartofaccounts',
            options={'verbose_name': 'Chart of Account'},
        ),
        migrations.AlterField(
            model_name='cashinflow',
            name='inflow_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='cashoutflow',
            name='account_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.ChartOfAccounts'),
        ),
        migrations.AlterField(
            model_name='cashoutflow',
            name='outflow_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='cashoutflow',
            name='ref_num',
            field=models.IntegerField(blank=True, verbose_name='Reference Number'),
        ),
    ]
