# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_auto_20161019_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashinflow',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='cashoutflow',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='cashinflow',
            name='ref_num',
            field=models.PositiveIntegerField(blank=True, verbose_name='Reference Number'),
        ),
        migrations.AlterField(
            model_name='cashoutflow',
            name='ref_num',
            field=models.PositiveIntegerField(blank=True, verbose_name='Reference Number'),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='ref_num',
            field=models.PositiveIntegerField(verbose_name='Reference Number'),
        ),
    ]
