# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_auto_20161020_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashoutflow',
            old_name='payor',
            new_name='payee',
        ),
    ]
