# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 06:28
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_auto_20161020_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalInflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_num', models.PositiveIntegerField(blank=True, verbose_name='Reference Number')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=29)),
                ('account_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.ChartOfAccounts', verbose_name='Account Title')),
            ],
        ),
        migrations.AlterField(
            model_name='cashinflow',
            name='account_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.ChartOfAccounts', verbose_name='Account Title'),
        ),
        migrations.AlterField(
            model_name='cashoutflow',
            name='account_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.ChartOfAccounts', verbose_name='Account Title'),
        ),
    ]
