# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_auto_20161020_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalinflow',
            name='account_title',
        ),
        migrations.DeleteModel(
            name='TotalInflow',
        ),
    ]
