# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 10:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_auto_20161020_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashinflow',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='cashoutflow',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
