# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_auto_20161029_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashinflow',
            old_name='inflow_type',
            new_name='flow_type',
        ),
        migrations.RenameField(
            model_name='cashoutflow',
            old_name='outflow_type',
            new_name='flow_type',
        ),
    ]
