# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_auto_20161030_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttypes',
            options={'verbose_name': 'Account Type'},
        ),
        migrations.AlterModelOptions(
            name='cashinflow',
            options={'ordering': ('-date',), 'verbose_name': 'Cash Inflow'},
        ),
        migrations.AlterModelOptions(
            name='cashoutflow',
            options={'ordering': ('-date',), 'verbose_name': 'Cash Outflow'},
        ),
        migrations.AlterModelOptions(
            name='chartofaccounts',
            options={'ordering': ('ref_num',), 'verbose_name': 'Chart of Account'},
        ),
        migrations.AddField(
            model_name='cashinflow',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
