# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_auto_20161106_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashinflow',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
