# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_auto_20161106_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashoutflow',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
