# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_auto_20161109_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashoutflow',
            name='account_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Account Title'),
        ),
        migrations.AlterField(
            model_name='cashoutflow',
            name='ref_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.ChartOfAccounts', to_field='ref_num', verbose_name='Reference Number'),
        ),
    ]
